                      List of relations
 Schema |          Name          | Type  |       Owner       
--------+------------------------+-------+-------------------
 public | agents_contacts        | table | nguyenngocson0811
 public | articles               | table | nguyenngocson0811
 public | assignments            | table | nguyenngocson0811
 public | autotask_details       | table | nguyenngocson0811
 public | autotasks              | table | nguyenngocson0811
 public | carts                  | table | nguyenngocson0811
 public | categories             | table | nguyenngocson0811
 public | categories_menus       | table | nguyenngocson0811
 public | categories_products    | table | nguyenngocson0811
 public | checkinout_requests    | table | nguyenngocson0811
 public | checkinouts            | table | nguyenngocson0811
 public | cities                 | table | nguyenngocson0811
 public | city_types             | table | nguyenngocson0811
 public | combination_details    | table | nguyenngocson0811
 public | combinations           | table | nguyenngocson0811
 public | commission_programs    | table | nguyenngocson0811
 public | contact_types          | table | nguyenngocson0811
 public | contact_types_contacts | table | nguyenngocson0811
 public | contacts               | table | nguyenngocson0811
 public | countries              | table | nguyenngocson0811
 public | customer_order_details | table | nguyenngocson0811
 public | customer_orders        | table | nguyenngocson0811
 public | deliveries             | table | nguyenngocson0811
 public | delivery_details       | table | nguyenngocson0811
 public | feedbacks              | table | nguyenngocson0811
 public | line_items             | table | nguyenngocson0811
 public | manages                | table | nguyenngocson0811
 public | manufacturers          | table | nguyenngocson0811
 public | menus                  | table | nguyenngocson0811
 public | messages               | table | nguyenngocson0811
 public | newsletters            | table | nguyenngocson0811
 public | notifications          | table | nguyenngocson0811
 public | order_details          | table | nguyenngocson0811
 public | order_statuses         | table | nguyenngocson0811
 public | order_statuses_orders  | table | nguyenngocson0811
 public | orders                 | table | nguyenngocson0811
 public | parent_categories      | table | nguyenngocson0811
 public | parent_contacts        | table | nguyenngocson0811
 public | parent_menus           | table | nguyenngocson0811
 public | payment_methods        | table | nguyenngocson0811
 public | payment_records        | table | nguyenngocson0811
 public | product_images         | table | nguyenngocson0811
 public | product_parts          | table | nguyenngocson0811
 public | product_prices         | table | nguyenngocson0811
 public | product_stock_updates  | table | nguyenngocson0811
 public | products               | table | nguyenngocson0811
 public | roles                  | table | nguyenngocson0811
 public | schema_migrations      | table | nguyenngocson0811
 public | slide_shows            | table | nguyenngocson0811
 public | states                 | table | nguyenngocson0811
 public | tags                   | table | nguyenngocson0811
 public | taxes                  | table | nguyenngocson0811
 public | tmpcats                | table | nguyenngocson0811
 public | tmpmanus               | table | nguyenngocson0811
 public | tmpproducts            | table | nguyenngocson0811
 public | tmpproducttocats       | table | nguyenngocson0811
 public | users                  | table | nguyenngocson0811
(57 rows)

